config/routes.rb
Rails.application.routes.draw do
  get 'searchs/searchR'
  get 'searchs/displayR'
  get 'starts/login'
  get 'starts/signup'
  get 'sign_up', to:'registrations#new'
  post 'sign_up', to:'registrations#create'
  get 'home/index', to:'homes#index'

  delete 'logout', to:'sessions#destroy'

  get 'sign_in', to:'sessions#new'
  post 'sign_in', to:'sessions#create'

  get '/home/search', to:'searchs#index'
  post '/home/search', to:'searchs#index'

  resources :subjects
  resources :courses
  resources :instructors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to:'starts#index'
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def index
        @parameter = params[:search]  
    #   @results = Course.all.where("name LIKE :search", search: @parameter)  
  

  end 
  def searchR
  end

  def displayR
  end
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/views/searchs/index.html.erb
<h1>This is a search page</h1>

<%= form_tag(home_search_path, :method => "get",   
    class: 'navbar-form navbar-left') do %>  
  <div class="input-group">  
    <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  
    <div class="input-group-btn">  
      <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
    </div>  
  </div>  
<% end %>
<br>
<br>
<br>
<br>
<br>
<br>
<hr>
<h3>dispaly text</h3>
<div>
<% if @parameter %>
<%= @parameter %>
<% end %>
</div>

app/views/searchs/searchR.html.erb
<h1>Searchs#searchR</h1>
<p>Find me in app/views/searchs/searchR.html.erb</p>